# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway

media_folder: "public/uploads" # Where images are stored
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
